name: Build Linux OneTracker App

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Linux App (.AppImage & .deb)
        run: npm run build:linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OneTracker-Linux-Release
          path: |
            dist/*.AppImage
            dist/*.deb